###
POST http://localhost:8000/api/users/
Content-Type: application/json

{   
    "username": "theo",
    "email": "jea@example.com",
    "password": "password"
}



###
GET http://localhost:8000/api/users/
Content-Type: application/json 

###
DELETE http://localhost:8000/api/users/1/
Content-Type: application/json 

